kind: PersistentVolume
apiVersion: v1
metadata:
  name: apisix-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/apisix"
